{% set company  = guest.system_company %}
{% set profile = client.client_get %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block meta_title %}{% endblock %} {{ settings.meta_title }}</title>

    <meta property="bb:url" content="{{ constant('BB_URL') }}"/>
    <meta property="bb:client_area" content="{{ '/'|link }}"/>
    
    <meta name="description" content="{% block meta_description %}{{ settings.meta_description }}{% endblock %}" />
    <meta name="keywords" content="{% block meta_keywords %}{{ settings.meta_keywords }}{% endblock %}" />
    <meta name="robots" content="{% if settings.meta_robots|default %}{{ settings.meta_robots }}{% else %}index, follow{% endif %}" />
	<meta name="author" content="{{ settings.meta_author }}">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <link rel="shortcut icon" href="{{ 'favicon.ico' | asset_url }}" />
	
	<!-- Bootstrap Core CSS -->
	{% if settings.theme != "default" %}<link href="{{ 'css/themes/theme-' | asset_url }}{{ settings.theme }}.min.css" rel="stylesheet">
	{% else %}<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">	
	{% endif %}

	<!-- Bootstrap Markdown Editor -->
    <link href="{{ 'css/bootstrap-markdown.min.css' | asset_url }}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{{ 'css/modern-business.css' | asset_url }}" rel="stylesheet">
	
	{% if settings.inject_css|default %}
	<!-- Custom CSS -->
	<style>
		{{ settings.inject_css|raw }}
	</style>
	{% endif %}

    <!-- Custom Fonts -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	
	<!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


	<!-- BoxBilling -->
    <script src="{{ 'js/bb-jquery.js' | asset_url }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
	

	<!-- Data Tables -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.16/js/jquery.dataTables.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.16/css/jquery.dataTables.min.css">

	<!-- Custom -->
    <link href="{{ 'css/custom.css' | asset_url }}" rel="stylesheet" type="text/css">
	<script src="{{ 'js/custom.js' | asset_url }}"></script>

	<!-- Bootstrap Markdown Editor -->
	<script src="{{ 'js/bootstrap-markdown.js' | asset_url }}"></script>
	<script src="{{ 'js/to-markdown.js' | asset_url }}"></script>
	<script src="{{ 'js/markdown.js' | asset_url }}"></script>

	<!-- Bootbox Alerts JavaScript -->
    <script src="{{ 'js/bootbox.min.js' | asset_url }}"></script>
	
	{% if settings.inject_javascript|default %}
	<!-- Custom Javascript -->
	<script>
		{{ settings.inject_javascript|raw }}
	</script>
	{% endif %}
	
	{% block js %}{% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block opengraph %}{% endblock %}
    {% block head %}{% endblock %}
</head>

<body>
{% if guest.extension_is_on({"mod":"cookieconsent"}) %}
    {% include 'mod_cookieconsent_index.phtml' ignore missing%}
{% endif %}

	<!-- Navigation -->
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header  animated-collapse-icon">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainmenu">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="sr-only">Toggle navigation</span>
                </button>
        <a class="navbar-brand hidden-xs" href="index.php">
			{% if company.logo_url %}<a href="{{ ''|link }}"><img src="{{company.logo_url}}" alt="{{company.name}}" id="company-logo" class="img-responsive"  style="width:auto; margin-left: 15px; padding-bottom: 10px;"/></a>
			{% else %}<h1><a href="{{ ''|link }}"><img src=" {{ 'images/logo_new.svg' | asset_url }}" alt="{{company.name}}" class="img-responsive" /></a></h1>
			{% endif %}		
		</a>
            </div>
		
            <!-- Collect the nav links, forms, and other content for toggling -->
            <nav class="collapse navbar-collapse" id="mainmenu"  role="navigation">
				<ul class="nav navbar-nav navbar-right">
					{% if settings.side_menu_home %}<li class="visible-xs"><a href="{{ ''|link }}" title="{% trans 'Home' %}" ><i class="fa fa-home"></i> {% trans 'Dashboard' %}</a></li>{% endif %}
					{% if client %}
					{% set profile = client.client_get %}
						{% if settings.side_menu_services %}<li class="visible-xs"><a href="{{ 'order/service'|link }}" title="{% trans 'Services' %}"><i class="fa fa-cog"></i> {% trans 'My Services' %}</a></li>{% endif %}
						{% if settings.side_menu_invoices %}<li class="visible-xs"><a href="{{ 'invoice'|link }}" title="{% trans 'Invoices' %}"><i class="fa fa-credit-card"></i> {% trans 'Invoices' %}</a></li>{% endif %}
						{% if settings.side_menu_support %}<li class="visible-xs"><a href="{{ 'support'|link }}" title="{% trans 'Tickets' %}"><i class="fa fa-life-ring"></i> {% trans 'Support Tickets' %}</a></li>{% endif %}
				
					{% else %}			
						<li><a href="" data-toggle="modal" data-target="#login"><i class="fa fa-user"></i> {% trans 'Sign in' %}</a></li>
						<li><a href="{{ 'login'|link({'register' : 1}) }}"><i class="fa fa-user-plus"></i> {% trans 'Register' %}</a></li>
					{% endif %}	
					{% if settings.side_menu_blog and guest.extension_is_on({"mod":"news"}) %}<li class="visible-xs"><a href="{{ '/news'|link }}" title="News" ><i class="fa fa-newspaper-o"></i> {% trans 'Announcements' %}</a></li>{% endif %}
					{% if settings.side_menu_forum and guest.extension_is_on({"mod":"forum"}) %}<li class="visible-xs"><a href="{{ '/forum'|link }}"><i class="fa fa-comments"></i> {% trans 'Forum' %}</a></li>{% endif %}
					{% if settings.side_menu_kb and guest.extension_is_on({"mod":"kb"}) %}<li class="visible-xs"><a href="{{ 'kb'|link }}" title="{% trans 'Knowledge Base' %}"><i class="fa fa-graduation-cap"></i> {% trans 'Knowledge Base' %}</a></li>{% endif %}
					{% if settings.side_menu_contact %}<li class="visible-xs"><a href="{{ '/support/contact-us'|link }}"><i class="fa fa-envelope"></i> {% trans 'Contact us' %}</a></li>{% endif %}
					<li role="separator" class="divider-vertical"></li>
					{% set cart = guest.cart_get %}				
					{% if settings.side_menu_order %}<li class="visible-xs"><a href="{{ '/order'|link }}" title="{% trans 'Order' %}" ><i class="fa fa-shopping-cart"></i> {% trans 'New Order' %}</a></li>{% endif %}
					<li><a href="{{ 'cart'|link }}" title="{% trans 'Shopping cart' %}"><i class="fa fa-shopping-cart"></i> {% trans 'Shopping cart' %}{% if cart.items|length > 0 %}<span class="badge">{{ cart.items|length }}</span>{% endif %}</a>
					  <span class="sr-only">items in cart</span></li>
					{% if client %}
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> {{ (profile.first_name ~ " " ~ profile.last_name) }} <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="{{ 'client/me'|link }}" title="{% trans 'Profile' %}"><i class="fa fa-user"></i> {% trans 'Manage profile' %}</a></li>
								{% if settings.show_client_emails %}<li><a href="{{ 'email'|link }}" title="{% trans 'Emails'%}"><i class="fa fa-envelope"></i> {% trans 'Emails'%}</a></li>{% endif %}
								{% if settings.show_client_balance %}<li><a href="{{ 'client/balance'|link }}"><i class="fa fa-bank"></i> {% trans 'Balance' %}: {{ profile.balance | money(profile.currency) }}</a></li>{% endif %}
								<li><a href="{{ 'client/logout'|link }}" title="{% trans 'Sign out' %}"><i class="fa fa-sign-out"></i> {% trans 'Sign out' %}</a></li>
							</ul>
						</li>
					{% endif %}
				</ul>
            </nav>
            <!-- /.navbar-collapse -->
			 
        </div>
        <!-- /.container -->
    </div>

{% block content_banner %}{% endblock %}


{% include "partial_menu.phtml" %}
		
<div class="container">
	<div class="row">

	{% if side_menu == 'hidden' %}
		<div class="col-sm-12">
	{% else %}
		<div class="col-sm-3" id="sidebar3">
			

			<!--{% set languages = guest.extension_languages %}
				{% if languages|length > 1 %}
					<h2>{% trans 'Select language' %}</h2>
							<select name="lang">
							{% for lang in languages %}
								<option value="{{ lang }}" >{{ lang|trans }}</option>
							{% endfor %}
							</select>
				{% endif %}-->
			

			{% if profile.first_name %}
			<div class="panel panel-default hidden-sm hidden-xs">
			  <div class="panel-heading"><i class="fa fa-user"></i>&nbsp;&nbsp;{% trans 'Your information' %}</div>
			  <div class="panel-body">
			  	<div class="fullname">{{ profile.first_name }} {{ profile.last_name }}</div>
			  	<div>{{ profile.address_1 }}</div>
			  	<div>{{ profile.address_2 }}</div>
			  	<div>{{ profile.city }}</div>
			  	<div>{{ profile.state }}</div>
			  	<div>{{ profile.postcode }}</div>
			  	<div>{{ profile.country }}</div>
			  </div>
			  <div class="panel-footer" align="center">
			  	<a class="footer-btn" href="{{ '/client/me' | link }}" ><i class="fa fa-pencil"></i>&nbsp;&nbsp;Update</a>
			  </div>
			</div>			
			{% endif %}

			<div class="panel panel-default">
			  <div class="panel-heading"><i class="fa fa-bookmark"></i>&nbsp;&nbsp;Shortcuts</div>
			  <div class="panel-body layanan">
			  		  <a href="{{ '/order'|link }}"><i class="fa fa-shopping-cart fa-fw"></i> {% trans 'Order New Services' %}</a>
  					  <a href="{{ '/order/domain-checker'|link }}"><i class="fa fa-globe fa-fw"></i> {% trans 'Order Domain' %} </a>
  					  {% if profile.first_name %}
  					  <a href="{{ 'client/logout'|link }}"><i class="fa fa-arrow-left fa-fw"></i> Logout </a>
  					  {% endif %}
			  </div>
			</div>			

			{% if settings.sidebar_note_enabled %}
            {% endif %}	

			{% if false %}
				{% block sidebar %}{% endblock %}
				{% block sidebar2 %}{% endblock %}
			{% endif %}
		</div>
		<div class="col-sm-9">
	{% endif %}	
			{% block content_before %}{% endblock %}
			{% include "partial_message.phtml" %}
			{% block content %}{% endblock %}
			{% block content_after %}{% endblock %}

			{% if not client %}
			<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="{% trans 'Login to client area' %}">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">{% trans 'Login to client area' %}</h4>
						</div>
						<div class="modal-body">
							<form action="" method="post" class="api_form" data-api-url="{{ 'api/guest/client/login'|link }}" data-api-reload="1">
								<div class="control-group form-group">
									<div class="controls">
										<label>{% trans 'Email address' %}:</label>
										<input type="email" class="form-control" name="email" value="{{ request.email }}" required="required" placeholder="{% trans 'Email address' %}">
									</div>
								</div>
								<div class="control-group form-group">
									<div class="controls">
										<label>{% trans 'Password' %}:</label>
										<input type="password" class="form-control" name="password" value="" required="required">
									</div>
								</div>
								<input type="hidden" name="remember" value="1" />
						</div>
						<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i></button>
								<a class="btn btn-success" href="{{ '/login'|link({'register' : 1}) }}">{% trans 'Create new account' %}</a>
								<a class="btn btn-warning" href="{{ 'reset-password'|link }}">{% trans 'Reset password' %}</a>
								<input class="btn btn-primary" type="submit" value="{% trans 'Sign in' %}">
							</form>
						</div>
					</div>
				</div>
			</div>
			{% endif %}
		</div>      
	</div>

	{% if settings.show_page_footer %}
        <!-- Footer -->
		<hr>
        <footer>
			<div class="row text-center">
				<div class="col-lg-12">
					<ul class="list-inline">
                        <li><a href="{{ '/about-us'|link }}">{% trans 'About us' %}</a></li>
                        <li><a href="{{ '/tos'|link }}">{% trans 'Terms and conditions' %}</a></li>
                        <li><a href="{{ '/privacy-policy'|link }}">{% trans 'Privacy policy' %}</a></li><br />
						{% for i in 1..5 %}
							{% if settings['footer_link_' ~ loop.index ~ '_enabled'] %}
							<li>
								{% if 'http://' in settings['footer_link_' ~ loop.index ~ '_page'] or  'https://' in settings['footer_link_' ~ loop.index ~ '_page'] %}
								<a href="{{ settings['footer_link_' ~ loop.index ~ '_page'] }}">{{ settings['footer_link_' ~ loop.index ~ '_title'] }}</a>
								{% else %}
								<a href="{{ settings['footer_link_' ~ loop.index ~ '_page'] | link }}">{{ settings['footer_link_' ~ loop.index ~ '_title'] }}</a>
								{% endif %}
							</li>
							{% endif %}
						{% endfor %}
						{# Removing this link is allowed only for BoxBilling PRO license owners. #}
						{% if guest.extension_is_on({"mod":'branding'}) or settings.footer_branding_enabled %}
							<li><a href="http://www.boxbilling.com" title="Billing Software" target="_blank">{% trans 'Powered by BoxBilling' %}</a></li>
						{% endif %}
                    </ul>
					<p>
						{% if settings.footer_signature|default %}{{ settings.footer_signature|raw }}
						{% else %}{{ company.name }} -  {{ company.signature }} &copy; {{ now|date('Y') }}
						{% endif %}
					</p>
					
				</div>
				{% if settings.footer_to_top_enabled %}<a href="#top" class="btn btn-default pull-right"><i class="fa fa-arrow-up"></i> {% trans 'Top' %}</a>{% endif %}
			</div>
        </footer>
	{% endif %}
    </div>
    <!-- /.container -->
    <div class="loading" id="loaderwrapper">
    	<div id="loaderwrapper2">
    		<div class="loader">

    		</div>
    		<p style="font-size : 18px; margin-top: 20px;">Processing Your Request. Please Wait...</p>
    	</div>
    </div>    
    
<noscript>NOTE: Many features on BoxBilling require Javascript and cookies. You can enable both via your browser's preference settings.</noscript>
</body>
</html>