{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}
    {% trans 'Order' %}
{% endblock %}

{% set periods = guest.system_periods %}

{% block content_before %}
		<!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{% trans 'Select Product' %}
                    <small>{% trans 'Choose products we offer for selling' %}</small>
                </h1>
				{% include "partial_steps.phtml" with {'selected': 1} %}
            </div>
        </div>
        <!-- /.row -->
{% endblock %}
{% block content %}

		<div class="row">
        <div class="col-lg-12">
            <div class="panel-group" id="accordion">
						{% for i, category in guest.product_category_get_list.list %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title category-title">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse-cat{{ category.id }}">
                                    <strong>{{ category.title }}</strong>
                                    {{ category.description|bbmd }}
                                    <i class="indicator glyphicon glyphicon-chevron-down  pull-right"></i>
                                </a>
                            </h4>
                        </div>
                        <div id="collapse-cat{{ category.id }}" class="panel-collapse collapse">
								{% set listing_template = 'mod_service'~category.type~'_listing.phtml' %}
								{% if guest.system_template_exists({"file":listing_template}) %}
								<div class="mod_service{{category.type}} panel-body">{% include listing_template %}</div>
								{% else %}
                                <ul class="list-group">
								{% for product in category.products %}
                                        <li class="list-group-item">
									<div class="row">
                                                <div class="col-md-8 text-wrap">
											<h4 class="list-group-item-heading order_title">{{ product.title }}</h4>

											<div class="list-group-item-text">
												{% if product.icon_url %}
												<div class="pull-left">
													{{ product.icon_url | img_tag }}
												</div>
												{% endif %}
												{{ product.description|bbmd }}
											</div>

										</div>
                                                <div class="col-md-4 text-center mt-5">
                                                    <p>
                                                        {# if product.pricing.type == 'recurrent' %}
                                                        												{% trans 'Starting from' %} 
                                                        												<select name="period" id="period-selector" class="form-control" disabled>
													{% for code,prices in product.pricing.recurrent %}
													{% if prices.enabled %}<option value="{{code}}">{{ prices.price | money_convert }} {{ periods[code] }}</option>{% endif %}
													{% endfor %}
												</select>	
                                                        											{% else %}{% endif #}
												<strong>{% trans 'Starting from' %}</strong>
												<br/> 
												<strong class="starting_price">{{ product.price_starting_from | money_convert }}</strong>
											</p>
											<div align="center">
                                                        <a class="btn btn-primary btn-order" href="{{ '/order'|link }}/{{ product.id }}">
                                                            <i class="fa fa-shopping-cart"></i>
                                                            {% trans 'Order now' %}</a>
										</div>
									</div>
								</div>
                                        </li>
								{% endfor %}
                                </ul>
								{% endif %}		

				
			</div>
		</div>
                    <!-- /.panel -->

                {% endfor %}

        			  </div>
            <!-- /.panel-group -->
        			</div>

    </div>
		
{% endblock %}

{% block sidebar %}
	<div class="well">
		{% include 'partial_currency.phtml' %}
	</div>
{% endblock %}


{% block js %}
    {% autoescape "js" %}
        <script type="text/javascript">

            $(document).ready(function () {
                function toggleChevron(e) {
                    $(e.target).prev('.panel-heading').find('i.indicator').toggleClass('glyphicon-chevron-down glyphicon-chevron-up');
                }
                $('#accordion').on('hide.bs.collapse show.bs.collapse', toggleChevron);

            });
        </script>
    {% endautoescape %}
{% endblock %}
