{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Proforma invoice' %}{% endblock %}


{% set nr = invoice.serie ~ "%05s"|format(invoice.nr) %}
{% set seller = invoice.seller %}
{% set buyer = invoice.buyer %}
{% set company  = guest.system_company %}

{% block content_before %}
		<!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
				{% if invoice.status == 'unpaid' %}
				<h1 class="page-header">{% trans 'Proforma Invoice' %}
					<small>{% trans 'Please choose payment type and pay for your chosen products.' %}</small>
				</h1>
				{% elseif invoice.status == "paid" %}
				<h1 class="page-header">{% trans 'Receipt' %} {{ nr }}
					<small>{% trans 'Invoice is paid' %}</small>
				</h1>
				{% endif %}
				<ol class="breadcrumb">
					<li><a href="{{ '/invoice'|link }}">{% trans 'Invoices' %}</a></li>
					<li class="active">{{ "Invoice #%05s"|format(invoice.id) }}</li>
				</ol>
            </div>
        </div>
        <!-- /.row -->
{% endblock %}
{% block content %}
	
	{% set banklink =  'invoice/banklink' | link %}
	{% if invoice.status == 'unpaid' %}
				<div class="row">
					<div class="col-lg-8 col-centered">
						<div class="well bg-info">
							<h4>{% trans 'Select Payment Method to View Details' %}</h4>
					<select name="payment_method" id="payment-selector" class="form-control">
    		    {% if invoice.gateway_id is null %}<option value="" selected disabled hidden>-- Select Payment Method --</option> {% endif%}
				{% for gtw in guest.invoice_gateways %}
    			{% if invoice.currency in gtw.accepted_currencies %}
		        <option data-value="{{ gtw | json_encode }}" value="{{gtw.id}}" {% if invoice.gateway_id == gtw.id %} selected {% endif %}>{{ gtw.title }}</option>
    			{% endif %}
    			{% endfor %}
				</select>
				<div class="text-center">
					<div class="panel-body" id="gtw-actions"></div>
					</div>
				</div>
				
				
				{% if invoice.gateway_id and request.auto_redirect %}
				{% set payment = guest.invoice_payment({"gateway_id" : invoice.gateway_id, "hash":invoice.hash, "auto_redirect":request.auto_redirect }) %}
					<div class="alert alert-info" id="payment-details">

						{% if payment.type == 'html' %}
						<div class="panel panel-primary">
						<div class="panel-body">								
							{{ include(template_from_string(payment.result)) }} 
							</div>
						</div>
							
						{% endif %}
							{% if payment.type == 'form' %}
							<h2>{% trans 'Redirecting to payment gateway..' %}</h2>
							<form name="payment_form" action="{{payment.service_url}}" method="post">
								{% for key, value in payment.result %}
								<input type="hidden" name="{{key}}" value="{{value}}" />
								{% endfor %}
								<input class="btn btn-warning" type="submit" value="{% trans 'Please click here to continue if this page does not redirect automatically in 5 seconds' %}" id="payment_button"/>
							</form>

							<script type="text/javascript">
								$(document).ready(function(){
									
									document.getElementById('payment_button').style.display = 'none';
									document.forms["payment_form"].submit();
								});
							</script>
							{% endif %}
					</div>
				{% endif %}

					</div>				
				</div>
				
				{% if request.change_payment_method %}
					<form method="post" action="{{ 'api/guest/invoice/update'|link }}" class="api-form" data-api-redirect="{{ ('invoice/'~invoice.hash)|link({'auto_redirect' : 1}) }}">
						<div class="list-group">
							{% for gtw in guest.invoice_gateways %}
								{% if invoice.currency in gtw.accepted_currencies %}
								<label class="list-group-item list-group-item">
									<input type="radio" name="gateway_id" value="{{gtw.id}}" {{loop.first ? 'checked' : ''}} />
									{% trans 'Pay by' %} {{gtw.title}}
									{% if gtw.title == "Custom" %}
										<i class="fa fa-university fa-2x pull-right"></i>
									{% elseif gtw.title == "PayPal" %}
										<i class="fa fa-paypal fa-2x pull-right"></i>
									{% elseif gtw.title == "Stripe" %}
										<i class="fa fa-cc-stripe fa-2x pull-right"></i>
									{% endif %}
								</label>
								{% endif %}
							{% endfor %}
						</div>
						<button class="btn btn-warning btn-lg" type="submit"><i class="fa fa-credit-card"></i> {% trans 'Pay Now' %} - {% trans 'Total:' %} <strong>{{ invoice.total | money(invoice.currency) }}</strong></button>
						<input type="hidden" name="hash" value="{{invoice.hash}}"/>
					</form>
				{% endif %}
	{% endif %}
	
		<div class="panel panel-default">
		<div class="panel-body">
		<div class="row">
			<div class="col-md-6">
				{% if company.logo_url %}
                <img src="{{company.logo_url}}" alt="{{company.name}}" style="max-width: 100%; max-height: 100%"/>
                {% else %}
                <img src=" {{ 'images/logo.png' | asset_url }}" alt="{{company.name}}" style="max-width: 100%; max-height: 100%"/>
                {% endif %}
			</div>
			<div class="col-md-6 text-right">
				<h2>{% if invoice.status == 'unpaid' %}{% trans 'Invoice' %} {% elseif invoice.status == "paid" %}{% trans 'Receipt' %} {% endif%}{{ invoice.serie_nr }}</h2>
                <p>
					{% if invoice.paid_at %}
					{% trans 'Paid at'%}:{{ invoice.paid_at | bb_date }}
					{% else %}
					{% trans 'Created' %}: {{ invoice.created_at | bb_date }}
					{% endif %}
                </p>
				<h2 class="invoice_{{invoice.status }}">{{ invoice.status|capitalize  }}</h2>
				{% trans 'Due' %}: {{ invoice.due_at | bb_date }}

			</div>
			<div class="col-md-12">
				<hr />
			</div>
			<div class="col-md-6">
				<address>
					{% if seller.company %}<strong>{{ seller.company }}</strong><br />{% endif %}
					{% if seller.address %}{{ seller.address }}<br />{% endif %}
					{% if seller.phone %}{{ seller.phone }}<br />{% endif %}
					{% if seller.email %}{{ seller.email }}<br />{% endif %}					
					{% if company.account_number %}{% trans 'Account' %}: {{ company.account_number }}<br />{% endif %}
					{% if company.number %}{% trans 'Company number' %}: {{ company.number }}<br />{% endif %}
					{% if company.vat_number %}{% trans 'VAT' %}: {{ company.vat_number }}<br />{% endif %}
					{# Company note #}{# if company.note %}{{ company.note }}<br />{% endif #}
				</address>
			</div>
			<div class="col-md-6 text-right">
				<address>
					{% if buyer.company %}<strong>{{ buyer.company }}</strong><br />{% endif %}
					{% if buyer.first_name or buyer.last_name %}<strong>{{ buyer.first_name }} {{ buyer.last_name }}</strong><br />{% endif %}
					{% if buyer.email %}{{ buyer.email }}<br />{% endif %}
					{% if buyer.address %}{{ buyer.address }} {{ buyer.city }} {{ buyer.state }} {{ buyer.postcode }} {{ buyer.country }}<br />{% endif %}					
					{% if buyer.phone %}{{ buyer.phone }}<br />{% endif %}
				</address>
			</div>
			
			{% if invoice.text_1 %}
			<div class="col-md-12">
				{{ invoice.text_1|markdown }}
			</div>
			{% endif %}

			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						{% trans 'Invoice' %}
					</div>
					<div class="panel-body">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>#</th>
									<th>{% trans 'Title' %}</th>
									<th class="currency">{% trans 'Amount' %}</th>
									<!--th class="currency">{% trans 'Total' %}</th-->
								</tr>
							</thead>

							<tbody>
								{% for i, item in invoice.lines %}

								<tr class="{{ cycle(['odd', 'even'], i) }}">
									<td>{{ i+1 }}.</td>
									<td>
										{% if item.order_id%}
										<a href="{{ '/order/service'|link }}/manage/{{item.order_id}}">{{ item.title }}</a>
										{% else %}
										{{ item.title }}
										{% endif %}
										{% if item.quantity > 1 %}
										x {{ item.quantity }} {# item.unit #}
										{% endif %}
									</td>
									<td class="currency">
										{{ item.total | money(invoice.currency) }}
									</td>
									<!--td class="currency">							
                    					{# if (item.price * item.quantity) > item.total #}
                    					{# set subtotal = item.price * item.quantity %}<del>{{subtotal}}</del> {% endif #}
										{{ item.total | money(invoice.currency) }}
									</td-->
								</tr>

								{% endfor %}
							</tbody>

							<tfoot>
							{% if invoice.tax > 0 %}
								<tr>
									<th colspan="2">{{ invoice.taxname }} {{ invoice.taxrate }}%</th>
									<th class="currency">{{ invoice.tax | money(invoice.currency) }}</th>
								</tr>
							{% endif %}
							
							{% if invoice.discount > 0 %}
								<tr>
									<th colspan="3">{% trans 'Discount' %}</th>
									<th class="currency">{{ invoice.discount | money(invoice.currency) }}</th>
								</tr>
							{% endif %}
								<tr class="total">
									<th colspan="2" class="text-right">{% trans 'Total' %}</th>
									<th class="currency">{{ invoice.total | money(invoice.currency) }}</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
			
			{% if invoice.text_2 %}
			<div class="col-md-12">
				{{ invoice.text_2|markdown }}
			</div>
			{% endif %}
			
		</div>
		</div>
		<div class="panel-footer text-center">
			<p>
				{% if invoice.status == 'unpaid' %}
				<!-- a class="btn btn-primary" href="{{ ('invoice/'~invoice.hash)|link({'change_payment_method' : 1}) }}"><i class="fa fa-credit-card"></i> {% trans 'Change payment method' %}</a -->
				{% endif %}
				<a class="btn btn-info" href="{{ 'invoice/print' | link }}/{{invoice.hash}}"><i class="fa fa-file-pdf-o"></i> {% trans 'Print' %}</a>
			</p>
		</div>
		</div>
<div class="text-center">
	<a class="btn btn-default" href="{{ '/invoice'|link }}"><i class="fa fa-arrow-left"></i> {% trans 'List of invoices' %}</a>
</div>
{% set transactions = client.invoice_transaction_get_list({"invoice_id":invoice.id, "type":"payment","per_page":100 }).list %}

{% if transactions|length > 0 %}

<div class="well">
    <h2>{% trans 'Transactions' %}</h2>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>{% trans 'Transaction Date' %}</th>
                <th>{% trans 'Transaction ID' %}</th>
                <th>{% trans 'Gateway' %}</th>
                <th>{% trans 'Amount' %}</th>
            </tr>
        </thead>

        <tbody>
            {% for i, tx in transactions %}
            <tr class="{{ cycle(['odd', 'even'], i) }}">
                <td>{{tx.created_at| bb_date }}</td>
                <td>{{tx.txn_id}}</td>
                <td>{{tx.gateway|default('-')}}</td>
                <td>{{ tx.amount | money(tx.currency) }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endif %}

{% endblock %}

{% block js %}


<script type="text/javascript">
$(document).ready(function(){

			$('#payment-selector').change(paymentMethodChanged);
			let options = $('#payment-selector option').length;			
			if(options > 0){
    			//$('#payment-selector').trigger('change');
				let gtw_id = $('#payment-selector').find(":selected").data("value").id;
				if(gtw_id){
				loadGtwActions(gtw_id);
				}
				else {
					$('#click-to-pay').addClass('hidden');
				}
			}
			else {
					$('#payment-selector').addClass('hidden');
					$('#gtw-actions').addClass('hidden');
				}
	});

	function paymentMethodChanged(event){
		$('#gtw-actions').html('');
		let gtw_id = $('#payment-selector').find(":selected").data("value").id;
		updateInvoice(gtw_id);
	}
	

	function loadGtwActions(gtway_id){			
				let btn = $(`<button type="button" class="btn btn-warning btn-lg {% if invoice.gateway_id and request.auto_redirect %}hidden{% endif %}" id="click-to-pay" > <i class="fa fa-credit-card"></i> {% trans "Pay now" %} - {% trans "Total:" %} <strong>{{ invoice.total | money(invoice.currency) }}</strong></button>`);
				$('#gtw-actions').html(btn);
				$('#click-to-pay').addClass('visible');

				$('#click-to-pay').on('click', function(){
					bb.redirect("{{ ('invoice/' ~ invoice.hash) | link({'gateway_id':"gtway_id",'auto_redirect':1}) }}" );
				});
	}

	function updateInvoice(gtw_id){		
        bb.post(
            '{{ 'api/guest/invoice/update'|link }}',
            {gateway_id:gtw_id, hash:'{{invoice.hash}}' },
            function(result) {
                bb.redirect("{{ ('invoice/' ~ invoice.hash) | link }}");
            }
        );
        return false;
    }
</script>
{% endblock %}
